name: Build Midori application

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm exec --yes @goastian/amelia -- download
      - run: npm exec --yes @goastian/amelia -- import
      - run: npm exec --yes @goastian/amelia -- build
